# Generated by Django 3.2 on 2021-12-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20211217_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='loftedpass',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='lowpass',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='placekicking',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
