# Generated by Django 3.2 on 2021-12-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20211218_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gk_awareness',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_catching',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_clearing',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_reach',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_reflexes',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='totalvalue',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
