# Generated by Django 3.2 on 2021-12-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20211219_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mostsuitableposition',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='suitableposition',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
