# Generated by Django 3.2 on 2021-12-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20211219_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='mostsuitableposition',
            new_name='mostsuitableposition_type',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='suitableposition',
            new_name='suitableposition_type',
        ),
    ]
