# Generated by Django 3.2 on 2021-12-21 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20211220_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCoach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('managementability', models.PositiveIntegerField()),
                ('adaptability', models.PositiveIntegerField()),
                ('formation', models.CharField(max_length=20)),
                ('offensivetype', models.CharField(choices=[('OFTYPE_C', 'Counter'), ('OFTYPE_P', 'Possessions'), ('BUILD_LP', 'LongPass'), ('BUILD_SP', 'ShortPass'), ('ATAREA_S', 'SideArea'), ('ATAREA_C', 'CenterArea'), ('POS_FLUID', 'Positionfluid'), ('POS_FIXED', 'Positionfixed'), ('DFTYPE_FORE', 'Forecheck'), ('DFTYPE_RET', 'Retreat'), ('DRIVEIN_C', 'driveinCenter'), ('DRIVEIN_S', 'driveinSide'), ('PRESS_AG', 'pressingAggressive'), ('PRESS_SA', 'pressingSafety')], max_length=100)),
                ('buildup', models.CharField(choices=[('OFTYPE_C', 'Counter'), ('OFTYPE_P', 'Possessions'), ('BUILD_LP', 'LongPass'), ('BUILD_SP', 'ShortPass'), ('ATAREA_S', 'SideArea'), ('ATAREA_C', 'CenterArea'), ('POS_FLUID', 'Positionfluid'), ('POS_FIXED', 'Positionfixed'), ('DFTYPE_FORE', 'Forecheck'), ('DFTYPE_RET', 'Retreat'), ('DRIVEIN_C', 'driveinCenter'), ('DRIVEIN_S', 'driveinSide'), ('PRESS_AG', 'pressingAggressive'), ('PRESS_SA', 'pressingSafety')], max_length=100)),
                ('attackarea', models.CharField(choices=[('OFTYPE_C', 'Counter'), ('OFTYPE_P', 'Possessions'), ('BUILD_LP', 'LongPass'), ('BUILD_SP', 'ShortPass'), ('ATAREA_S', 'SideArea'), ('ATAREA_C', 'CenterArea'), ('POS_FLUID', 'Positionfluid'), ('POS_FIXED', 'Positionfixed'), ('DFTYPE_FORE', 'Forecheck'), ('DFTYPE_RET', 'Retreat'), ('DRIVEIN_C', 'driveinCenter'), ('DRIVEIN_S', 'driveinSide'), ('PRESS_AG', 'pressingAggressive'), ('PRESS_SA', 'pressingSafety')], max_length=100)),
                ('positioning', models.CharField(choices=[('OFTYPE_C', 'Counter'), ('OFTYPE_P', 'Possessions'), ('BUILD_LP', 'LongPass'), ('BUILD_SP', 'ShortPass'), ('ATAREA_S', 'SideArea'), ('ATAREA_C', 'CenterArea'), ('POS_FLUID', 'Positionfluid'), ('POS_FIXED', 'Positionfixed'), ('DFTYPE_FORE', 'Forecheck'), ('DFTYPE_RET', 'Retreat'), ('DRIVEIN_C', 'driveinCenter'), ('DRIVEIN_S', 'driveinSide'), ('PRESS_AG', 'pressingAggressive'), ('PRESS_SA', 'pressingSafety')], max_length=100)),
                ('defensivetype', models.CharField(choices=[('OFTYPE_C', 'Counter'), ('OFTYPE_P', 'Possessions'), ('BUILD_LP', 'LongPass'), ('BUILD_SP', 'ShortPass'), ('ATAREA_S', 'SideArea'), ('ATAREA_C', 'CenterArea'), ('POS_FLUID', 'Positionfluid'), ('POS_FIXED', 'Positionfixed'), ('DFTYPE_FORE', 'Forecheck'), ('DFTYPE_RET', 'Retreat'), ('DRIVEIN_C', 'driveinCenter'), ('DRIVEIN_S', 'driveinSide'), ('PRESS_AG', 'pressingAggressive'), ('PRESS_SA', 'pressingSafety')], max_length=100)),
                ('driveinarea', models.CharField(choices=[('OFTYPE_C', 'Counter'), ('OFTYPE_P', 'Possessions'), ('BUILD_LP', 'LongPass'), ('BUILD_SP', 'ShortPass'), ('ATAREA_S', 'SideArea'), ('ATAREA_C', 'CenterArea'), ('POS_FLUID', 'Positionfluid'), ('POS_FIXED', 'Positionfixed'), ('DFTYPE_FORE', 'Forecheck'), ('DFTYPE_RET', 'Retreat'), ('DRIVEIN_C', 'driveinCenter'), ('DRIVEIN_S', 'driveinSide'), ('PRESS_AG', 'pressingAggressive'), ('PRESS_SA', 'pressingSafety')], max_length=100)),
                ('pressing', models.CharField(choices=[('OFTYPE_C', 'Counter'), ('OFTYPE_P', 'Possessions'), ('BUILD_LP', 'LongPass'), ('BUILD_SP', 'ShortPass'), ('ATAREA_S', 'SideArea'), ('ATAREA_C', 'CenterArea'), ('POS_FLUID', 'Positionfluid'), ('POS_FIXED', 'Positionfixed'), ('DFTYPE_FORE', 'Forecheck'), ('DFTYPE_RET', 'Retreat'), ('DRIVEIN_C', 'driveinCenter'), ('DRIVEIN_S', 'driveinSide'), ('PRESS_AG', 'pressingAggressive'), ('PRESS_SA', 'pressingSafety')], max_length=100)),
            ],
        ),
    ]
