# Generated by Django 3.2 on 2021-12-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_headcoach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headcoach',
            name='attackarea',
            field=models.CharField(choices=[('ATAREA_S', 'SideArea'), ('ATAREA_C', 'CenterArea')], max_length=100),
        ),
        migrations.AlterField(
            model_name='headcoach',
            name='buildup',
            field=models.CharField(choices=[('BUILD_LP', 'LongPass'), ('BUILD_SP', 'ShortPass')], max_length=100),
        ),
        migrations.AlterField(
            model_name='headcoach',
            name='defensivetype',
            field=models.CharField(choices=[('DFTYPE_FORE', 'Forecheck'), ('DFTYPE_RET', 'Retreat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='headcoach',
            name='driveinarea',
            field=models.CharField(choices=[('DRIVEIN_C', 'driveinCenter'), ('DRIVEIN_S', 'driveinSide')], max_length=100),
        ),
        migrations.AlterField(
            model_name='headcoach',
            name='offensivetype',
            field=models.CharField(choices=[('OFTYPE_C', 'Counter'), ('OFTYPE_P', 'Possessions')], max_length=100),
        ),
        migrations.AlterField(
            model_name='headcoach',
            name='positioning',
            field=models.CharField(choices=[('POS_FLUID', 'Positionfluid'), ('POS_FIXED', 'Positionfixed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='headcoach',
            name='pressing',
            field=models.CharField(choices=[('PRESS_AG', 'pressingAggressive'), ('PRESS_SA', 'pressingSafety')], max_length=100),
        ),
    ]
