# Generated by Django 3.2 on 2021-12-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20211221_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headcoach',
            old_name='name',
            new_name='headcoachname',
        ),
    ]
