# Generated by Django 3.2 on 2021-12-22 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_rename_name_headcoach_headcoachname'),
    ]

    operations = [
        migrations.AddField(
            model_name='headcoach',
            name='cf_value',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
