# Generated by Django 3.2 on 2021-12-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_auto_20211222_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='headcoach',
            name='formationimage',
            field=models.ImageField(blank=True, upload_to='images/headcoaches/'),
        ),
        migrations.AddField(
            model_name='headcoach',
            name='playerimage',
            field=models.ImageField(default='images/headCoaches/HeadCoachDefaultImage.png', upload_to='images/headcoaches/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='playerimage',
            field=models.ImageField(blank=True, upload_to='images/players/'),
        ),
    ]
