# Generated by Django 3.2 on 2021-12-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_auto_20211222_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headcoach',
            old_name='playerimage',
            new_name='headcoachimage',
        ),
    ]
