# Generated by Django 3.2 on 2022-03-01 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_rename_playerimage_headcoach_headcoachimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='type',
            field=models.CharField(choices=[('LE', 'Legend'), ('IM', 'Iconic'), ('FP', 'Featured')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
